/-
SPDX-License-Identifier: Apache-2.0
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
-- Contributors: Formalization Worker A, Formalization Worker B, Prism.
-- See README.md for internal reuse.
module

public import SphereTopology.Homology.Singular.Subdivision
public import Mathlib.AlgebraicTopology.SingularHomology.Basic
public import Mathlib.AlgebraicTopology.SimplicialSet.Subcomplex
public import Mathlib.AlgebraicTopology.SimplicialSet.TopAdj
public import Mathlib.Algebra.Homology.QuasiIso
public import Mathlib.Algebra.Category.ModuleCat.Colimits
public import Mathlib.Algebra.Category.ModuleCat.Ulift
public import Mathlib.Topology.Sets.OpenCover
public import Mathlib.Algebra.Homology.ShortComplex.ModuleCat

/-!
# Singular chains small relative to an open cover

For an open cover `U`, this file defines the simplicial subset of singular
simplices whose image lies in one member of `U`, its integer chain complex, and
the inclusion into ordinary singular chains.  Iterated barycentric subdivision
and its support-preserving prism homotopy prove that this inclusion is a
quasi-isomorphism.

No nonemptiness hypothesis is imposed on the space or the cover index.
-/

@[expose] public section

open CategoryTheory
open Convexity TopologicalSpace
open scoped Simplicial

noncomputable section

universe u

namespace TopCat

/-- Singular simplices whose range is contained in one member of `U`. -/
def smallSingularSet {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X) :
    (TopCat.toSSet.obj X).Subcomplex where
  obj n := {x | ∃ i, Set.range (X.toSSetObjEquiv n x) ⊆ U i}
  map {n m} f x hx := by
    rcases hx with ⟨i, hi⟩
    refine ⟨i, ?_⟩
    rintro _ ⟨z, rfl⟩
    exact hi ⟨StdSimplex.map f.unop z, rfl⟩

theorem mem_smallSingularSet_iff {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X)
    {n : SimplexCategoryᵒᵖ} (x : (TopCat.toSSet.obj X).obj n) :
    x ∈ (smallSingularSet U).obj n ↔
      ∃ i, Set.range (X.toSSetObjEquiv n x) ⊆ U i :=
  Iff.rfl

/-- Refining every member of `U` into a member of `V` gives an inclusion of
the corresponding small-singular subcomplexes. -/
theorem smallSingularSet_mono {X : TopCat.{u}} {ι κ : Type*}
    {U : ι → Opens X} {V : κ → Opens X}
    (h : ∀ i, ∃ j, U i ≤ V j) : smallSingularSet U ≤ smallSingularSet V := by
  intro n x hx
  obtain ⟨i, hi⟩ := hx
  obtain ⟨j, hj⟩ := h i
  exact ⟨j, hi.trans hj⟩

/-- The simplicial map on small singular sets induced by a cover refinement. -/
def smallSingularSetHomOfRefinement {X : TopCat.{u}} {ι κ : Type*}
    {U : ι → Opens X} {V : κ → Opens X}
    (h : ∀ i, ∃ j, U i ≤ V j) :
    (smallSingularSet U : SSet.{u}) ⟶ (smallSingularSet V : SSet.{u}) :=
  SSet.Subcomplex.homOfLE (smallSingularSet_mono h)

/-- A continuous map induces a map of small-singular simplicial sets whenever
it sends each member of the source cover into a member of the target cover. -/
def smallSingularSetMap {X Y : TopCat.{u}} {ι κ : Type*}
    (f : X ⟶ Y) (U : ι → Opens X) (V : κ → Opens Y)
    (h : ∀ i, ∃ j, Set.MapsTo f (U i) (V j)) :
    (smallSingularSet U : SSet.{u}) ⟶ (smallSingularSet V : SSet.{u}) where
  app n := ↾fun x => ⟨(TopCat.toSSet.map f).app n x.1, by
    obtain ⟨i, hi⟩ := x.2
    obtain ⟨j, hj⟩ := h i
    refine ⟨j, ?_⟩
    rintro _ ⟨z, rfl⟩
    apply hj
    apply hi
    exact ⟨z, rfl⟩⟩
  naturality _ _ _ := by rfl

@[reassoc]
theorem smallSingularSetMap_comp_inclusion {X Y : TopCat.{u}} {ι κ : Type*}
    (f : X ⟶ Y) (U : ι → Opens X) (V : κ → Opens Y)
    (h : ∀ i, ∃ j, Set.MapsTo f (U i) (V j)) :
    smallSingularSetMap f U V h ≫ (smallSingularSet V).ι =
      (smallSingularSet U).ι ≫ TopCat.toSSet.map f := by
  rfl

end TopCat

namespace AlgebraicTopology

/-- Integer coefficients lifted into the universe of the singular simplices.
The underlying module is canonically linearly equivalent to `ℤ`. -/
abbrev integerCoefficients : ModuleCat.{u} ℤ :=
  (ModuleCat.uliftFunctor.{u} ℤ).obj (ModuleCat.of ℤ ℤ)

/-- Every singular zero-simplex is small relative to an open cover. -/
theorem isCoverSmall_zero {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X)
    (hU : IsOpenCover U) (x : (TopCat.toSSet.obj X) _⦋0⦌) :
    IsCoverSmall U x := by
  obtain ⟨i, hi⟩ := hU.exists_mem (X.toSSetObjEquiv _ x default)
  refine ⟨i, ?_⟩
  rintro _ ⟨z, rfl⟩
  rw [Subsingleton.elim z default]
  exact hi

/-- The integer chain complex generated by singular simplices small in `U`. -/
def smallSingularChainComplex {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X) :
    ChainComplex (ModuleCat.{u} ℤ) ℕ :=
  ((TopCat.smallSingularSet U : SSet.{u}).chainComplex integerCoefficients)

/-- Inclusion of the `U`-small integer singular chain complex into all chains. -/
def smallSingularChainInclusion {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X) :
    smallSingularChainComplex U ⟶
      ((singularChainComplexFunctor (ModuleCat.{u} ℤ)).obj integerCoefficients).obj X :=
  SSet.chainComplexMap (SSet.Subcomplex.ι (TopCat.smallSingularSet U)) integerCoefficients

/-- The integer-chain map induced by a refinement of open covers. -/
def smallSingularChainMapOfRefinement {X : TopCat.{u}} {ι κ : Type*}
    {U : ι → Opens X} {V : κ → Opens X}
    (h : ∀ i, ∃ j, U i ≤ V j) :
    smallSingularChainComplex U ⟶ smallSingularChainComplex V :=
  SSet.chainComplexMap (TopCat.smallSingularSetHomOfRefinement h) integerCoefficients

@[reassoc]
theorem smallSingularChainMapOfRefinement_comp_inclusion
    {X : TopCat.{u}} {ι κ : Type*} {U : ι → Opens X} {V : κ → Opens X}
    (h : ∀ i, ∃ j, U i ≤ V j) :
    smallSingularChainMapOfRefinement h ≫ smallSingularChainInclusion V =
      smallSingularChainInclusion U := by
  apply HomologicalComplex.hom_ext _ _
  intro n
  apply SSet.chainComplex_hom_ext
  intro x
  dsimp [smallSingularChainMapOfRefinement, smallSingularChainInclusion,
    smallSingularChainComplex, singularChainComplexFunctor]
  rw [← Category.assoc, SSet.ι_chainComplexMap_f]
  rw [SSet.ι_chainComplexMap_f]
  rw [SSet.ι_chainComplexMap_f]
  rfl

/-- The chain map on cover-small chains induced by a cover-respecting
continuous map. -/
def smallSingularChainMap {X Y : TopCat.{u}} {ι κ : Type*}
    (f : X ⟶ Y) (U : ι → Opens X) (V : κ → Opens Y)
    (h : ∀ i, ∃ j, Set.MapsTo f (U i) (V j)) :
    smallSingularChainComplex U ⟶ smallSingularChainComplex V :=
  SSet.chainComplexMap (TopCat.smallSingularSetMap f U V h) integerCoefficients

@[reassoc]
theorem smallSingularChainMap_comp_inclusion {X Y : TopCat.{u}} {ι κ : Type*}
    (f : X ⟶ Y) (U : ι → Opens X) (V : κ → Opens Y)
    (h : ∀ i, ∃ j, Set.MapsTo f (U i) (V j)) :
    smallSingularChainMap f U V h ≫ smallSingularChainInclusion V =
      smallSingularChainInclusion U ≫
        SSet.chainComplexMap (TopCat.toSSet.map f) integerCoefficients := by
  apply HomologicalComplex.hom_ext _ _
  intro n
  apply SSet.chainComplex_hom_ext
  intro x
  dsimp [smallSingularChainMap, smallSingularChainInclusion,
    smallSingularChainComplex, singularChainComplexFunctor]
  rw [← Category.assoc, SSet.ι_chainComplexMap_f]
  rw [SSet.ι_chainComplexMap_f]
  rw [← Category.assoc, SSet.ι_chainComplexMap_f]
  rw [SSet.ι_chainComplexMap_f]
  rfl

/-- Identify the degree-`n` integer-coefficient simplicial chain group with
finitely supported integer functions on the `n`-simplices. The construction
also removes the coefficient `ULift` used to accommodate the universe of `X`. -/
noncomputable def chainGroupIsoFinsupp (X : SSet.{u}) (n : ℕ) :
    (X.chainComplex integerCoefficients).X n ≅
      ModuleCat.of ℤ (X _⦋n⦌ →₀ ℤ) := by
  let e₁ := (X.isColimitChainComplexXCofan integerCoefficients n).coconePointUniqueUpToIso
    (ModuleCat.finsuppCoconeIsColimit ℤ (ULift ℤ) (X _⦋n⦌))
  let e₂ : ModuleCat.of ℤ (X _⦋n⦌ →₀ ULift.{u} ℤ) ≅
      ModuleCat.of ℤ (X _⦋n⦌ →₀ ℤ) :=
    (Finsupp.mapRange.linearEquiv (ULift.moduleEquiv (R := ℤ) (M := ℤ))).toModuleIso
  exact e₁ ≪≫ e₂

set_option backward.isDefEq.respectTransparency false in
theorem ι_chainGroupIsoFinsupp_hom (X : SSet.{u}) {n : ℕ} (x : X _⦋n⦌) :
    X.ιChainComplex (R := integerCoefficients) x ≫ (chainGroupIsoFinsupp X n).hom =
      ModuleCat.ofHom ((Finsupp.lsingle x).comp ULift.moduleEquiv.toLinearMap) := by
  let e₂ : ModuleCat.of ℤ (X _⦋n⦌ →₀ ULift.{u} ℤ) ≅
      ModuleCat.of ℤ (X _⦋n⦌ →₀ ℤ) :=
    (Finsupp.mapRange.linearEquiv (ULift.moduleEquiv (R := ℤ) (M := ℤ))).toModuleIso
  have h := (X.isColimitChainComplexXCofan integerCoefficients n)
    |>.comp_coconePointUniqueUpToIso_hom
      (ModuleCat.finsuppCoconeIsColimit ℤ (ULift ℤ) (X _⦋n⦌)) ⟨x⟩
  have h' := congrArg (fun f ↦ f ≫ e₂.hom) h
  calc
    _ = (ModuleCat.finsuppCocone ℤ (ULift ℤ) (X _⦋n⦌)).ι.app ⟨x⟩ ≫ e₂.hom := by
      rw [chainGroupIsoFinsupp, Iso.trans_hom, ← Category.assoc]
      exact h'
    _ = ModuleCat.ofHom ((Finsupp.lsingle x).comp ULift.moduleEquiv.toLinearMap) := by
      apply ModuleCat.hom_ext
      apply LinearMap.ext
      intro z
      simp [e₂, ModuleCat.finsuppCocone]

@[simp]
theorem chainGroupIsoFinsupp_hom_ι (X : SSet.{u}) {n : ℕ} (x : X _⦋n⦌) :
    (chainGroupIsoFinsupp X n).hom.hom
        ((X.ιChainComplex (R := integerCoefficients) x).hom (ULift.up (1 : ℤ))) =
      Finsupp.single x 1 := by
  have h := ι_chainGroupIsoFinsupp_hom X x
  have h1 := congr($h (ULift.up (1 : ℤ)))
  change (chainGroupIsoFinsupp X n).hom.hom
      ((X.ιChainComplex (R := integerCoefficients) x).hom (ULift.up (1 : ℤ))) =
        Finsupp.single x 1 at h1
  exact h1

end AlgebraicTopology
open CategoryTheory Convexity TopologicalSpace
open scoped Simplicial

noncomputable section

namespace AlgebraicTopology

theorem moduleCat_quasiIso_of_representatives
    {S₁ S₂ : ShortComplex (ModuleCat.{u} ℤ)} (φ : S₁ ⟶ S₂)
    [S₁.HasHomology] [S₂.HasHomology]
    (hsurj : ∀ (y : S₂.X₂), S₂.g y = 0 →
      ∃ x : S₁.X₂, S₁.g x = 0 ∧
        ∃ b : S₂.X₁, φ.τ₂ x - y = S₂.f b)
    (hinj : ∀ (x : S₁.X₂), S₁.g x = 0 →
      ∀ b : S₂.X₁, φ.τ₂ x = S₂.f b →
        ∃ a : S₁.X₁, x = S₁.f a) :
    ShortComplex.QuasiIso φ := by
  let h₁ := S₁.moduleCatLeftHomologyData
  let h₂ := S₂.moduleCatLeftHomologyData
  let γ : ShortComplex.LeftHomologyMapData φ h₁ h₂ := default
  rw [γ.quasiIso_iff, ConcreteCategory.isIso_iff_bijective]
  constructor
  · intro q₁ q₂
    refine QuotientAddGroup.induction_on q₁ (fun x₁ ↦ ?_)
    refine QuotientAddGroup.induction_on q₂ (fun x₂ hq ↦ ?_)
    have hmap₁ : γ.φH (h₁.π x₁) = h₂.π (γ.φK x₁) := by
      change (h₁.π ≫ γ.φH) x₁ = (γ.φK ≫ h₂.π) x₁
      rw [γ.commπ]
    have hmap₂ : γ.φH (h₁.π x₂) = h₂.π (γ.φK x₂) := by
      change (h₁.π ≫ γ.φH) x₂ = (γ.φK ≫ h₂.π) x₂
      rw [γ.commπ]
    change γ.φH (h₁.π x₁) = γ.φH (h₁.π x₂) at hq
    rw [hmap₁, hmap₂] at hq
    have hrange := QuotientAddGroup.eq_iff_sub_mem.mp hq
    obtain ⟨b, hb⟩ := hrange
    have hφK₁ : h₂.i (γ.φK x₁) = φ.τ₂ (h₁.i x₁) := by
      have h := congr($(γ.commi) x₁)
      change h₂.i (γ.φK x₁) = φ.τ₂ (h₁.i x₁) at h
      exact h
    have hφK₂ : h₂.i (γ.φK x₂) = φ.τ₂ (h₁.i x₂) := by
      have h := congr($(γ.commi) x₂)
      change h₂.i (γ.φK x₂) = φ.τ₂ (h₁.i x₂) at h
      exact h
    have hxcycle : S₁.g ((x₁ : S₁.X₂) - x₂) = 0 := by
      rw [map_sub]
      change S₁.g x₁ - S₁.g x₂ = 0
      simp
    have hboundary : φ.τ₂ ((x₁ : S₁.X₂) - x₂) = S₂.f b := by
      rw [map_sub]
      change φ.τ₂ (x₁ : S₁.X₂) - φ.τ₂ (x₂ : S₁.X₂) = S₂.f b
      change φ.τ₂ (h₁.i x₁) - φ.τ₂ (h₁.i x₂) = S₂.f b
      rw [← hφK₁, ← hφK₂]
      exact congr_arg Subtype.val hb.symm
    obtain ⟨a, ha⟩ := hinj ((x₁ : S₁.X₂) - x₂) hxcycle b hboundary
    apply QuotientAddGroup.eq_iff_sub_mem.mpr
    refine ⟨a, ?_⟩
    apply Subtype.ext
    exact ha.symm
  · intro q
    refine QuotientAddGroup.induction_on q (fun y ↦ ?_)
    obtain ⟨x, hxcycle, b, hxb⟩ := hsurj (y : S₂.X₂) y.property
    let x' : LinearMap.ker S₁.g.hom := ⟨x, hxcycle⟩
    refine ⟨h₁.π x', ?_⟩
    have hmap : γ.φH (h₁.π x') = h₂.π (γ.φK x') := by
      change (h₁.π ≫ γ.φH) x' = (γ.φK ≫ h₂.π) x'
      rw [γ.commπ]
    rw [hmap]
    apply QuotientAddGroup.eq_iff_sub_mem.mpr
    refine ⟨b, ?_⟩
    apply Subtype.ext
    have hφK : h₂.i (γ.φK x') = φ.τ₂ (h₁.i x') := by
      have h := congr($(γ.commi) x')
      change h₂.i (γ.φK x') = φ.τ₂ (h₁.i x') at h
      exact h
    change S₂.f b = h₂.i (γ.φK x') - y
    rw [hφK]
    exact hxb.symm

/-- The integer-linear boundary from degree `n + 1` to degree `n`, sending a
simplex to the alternating face sum with coefficient `(-1)^i` on its `i`th face. -/
def sSetFinsuppBoundary (Z : SSet.{u}) (n : ℕ) :
    (Z _⦋n + 1⦌ →₀ ℤ) →ₗ[ℤ] (Z _⦋n⦌ →₀ ℤ) :=
  Finsupp.lift (Z _⦋n⦌ →₀ ℤ) ℤ (Z _⦋n + 1⦌)
    (fun x ↦ ∑ i : Fin (n + 2), (-1 : ℤ) ^ i.val • Finsupp.single (Z.δ i x) 1)

@[simp]
theorem sSetFinsuppBoundary_single (Z : SSet.{u}) (n : ℕ) (x : Z _⦋n + 1⦌) :
    sSetFinsuppBoundary Z n (Finsupp.single x 1) =
      ∑ i : Fin (n + 2), (-1 : ℤ) ^ i.val • Finsupp.single (Z.δ i x) 1 := by
  simp [sSetFinsuppBoundary]

theorem chainGroupIsoFinsupp_sSet_d (Z : SSet.{u}) (n : ℕ) :
    (chainGroupIsoFinsupp Z (n + 1)).inv ≫
        (Z.chainComplex integerCoefficients).d (n + 1) n ≫
        (chainGroupIsoFinsupp Z n).hom =
      ModuleCat.ofHom (sSetFinsuppBoundary Z n) := by
  rw [← cancel_epi (chainGroupIsoFinsupp Z (n + 1)).hom]
  simp only [Iso.hom_inv_id_assoc]
  apply SSet.chainComplex_hom_ext
  intro x
  rw [← Category.assoc, SSet.ιChainComplex_d]
  simp only [Preadditive.sum_comp, Preadditive.zsmul_comp,
    ι_chainGroupIsoFinsupp_hom]
  rw [← Category.assoc, ι_chainGroupIsoFinsupp_hom]
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro z
  simp only [ModuleCat.hom_sum, LinearMap.sum_apply]
  change (∑ i : Fin (n + 2), (-1 : ℤ) ^ i.val • Finsupp.single (Z.δ i x) z.down) =
    sSetFinsuppBoundary Z n (Finsupp.single x z.down)
  have hz : Finsupp.single x z.down = z.down • Finsupp.single x 1 := by simp
  rw [hz, map_smul, sSetFinsuppBoundary_single, Finset.smul_sum]
  apply Finset.sum_congr rfl
  intro i hi
  simp only [Finsupp.smul_single]
  congr 1
  ring

theorem chainGroupIsoFinsupp_sSet_d_apply (Z : SSet.{u}) (n : ℕ)
    (c : Z _⦋n + 1⦌ →₀ ℤ) :
    (chainGroupIsoFinsupp Z n).hom
        ((Z.chainComplex integerCoefficients).d (n + 1) n
          ((chainGroupIsoFinsupp Z (n + 1)).inv c)) =
      sSetFinsuppBoundary Z n c := by
  have h := chainGroupIsoFinsupp_sSet_d Z n
  have hc := congr($h c)
  simpa only [ConcreteCategory.comp_apply, Iso.inv_hom_id_apply,
    ModuleCat.hom_ofHom] using hc

theorem mapDomain_smallFinsuppBoundary
    {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X) (n : ℕ)
    (c : (TopCat.smallSingularSet U : SSet.{u}) _⦋n + 1⦌ →₀ ℤ) :
    Finsupp.mapDomain Subtype.val
        (sSetFinsuppBoundary (TopCat.smallSingularSet U : SSet.{u}) n c) =
      singularFinsuppBoundary X n (Finsupp.mapDomain Subtype.val c) := by
  induction c using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg => simp only [map_add, Finsupp.mapDomain_add, hf, hg]
  | single x z =>
      have hc : Finsupp.single x z = z • Finsupp.single x 1 := by simp
      rw [hc]
      simp only [map_smul, Finsupp.mapDomain_smul,
        sSetFinsuppBoundary_single, Finsupp.mapDomain_single,
        singularFinsuppBoundary_single]
      rw [Finsupp.mapDomain_finsetSum]
      congr 1
      apply Finset.sum_congr rfl
      intro i hi
      rw [Finsupp.mapDomain_smul, Finsupp.mapDomain_single]
      congr 1

theorem chainGroupIsoFinsupp_d (X : TopCat.{u}) (n : ℕ) :
    (chainGroupIsoFinsupp (TopCat.toSSet.obj X) (n + 1)).inv ≫
        ((TopCat.toSSet.obj X).chainComplex integerCoefficients).d (n + 1) n ≫
        (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom =
      ModuleCat.ofHom (singularFinsuppBoundary X n) := by
  rw [← cancel_epi (chainGroupIsoFinsupp (TopCat.toSSet.obj X) (n + 1)).hom]
  simp only [Iso.hom_inv_id_assoc]
  apply SSet.chainComplex_hom_ext
  intro x
  rw [← Category.assoc, SSet.ιChainComplex_d]
  simp only [Preadditive.sum_comp, Preadditive.zsmul_comp,
    ι_chainGroupIsoFinsupp_hom]
  rw [← Category.assoc, ι_chainGroupIsoFinsupp_hom]
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro z
  simp only [ModuleCat.hom_sum, LinearMap.sum_apply]
  change (∑ i : Fin (n + 2), (-1 : ℤ) ^ i.val •
      Finsupp.single ((TopCat.toSSet.obj X).δ i x) z.down) =
    singularFinsuppBoundary X n (Finsupp.single x z.down)
  have hz : Finsupp.single x z.down = z.down • Finsupp.single x 1 := by simp
  rw [hz, map_smul, singularFinsuppBoundary_single, Finset.smul_sum]
  apply Finset.sum_congr rfl
  intro i hi
  simp only [Finsupp.smul_single]
  congr 1
  ring

theorem chainGroupIsoFinsupp_smallInclusion
    {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X) (n : ℕ) :
    (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).inv ≫
        (smallSingularChainInclusion U).f n ≫
        (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom =
      ModuleCat.ofHom (Finsupp.lmapDomain ℤ ℤ Subtype.val) := by
  rw [← cancel_epi (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).hom]
  simp only [Iso.hom_inv_id_assoc]
  apply SSet.chainComplex_hom_ext
  intro x
  dsimp [smallSingularChainInclusion, smallSingularChainComplex,
    singularChainComplexFunctor]
  rw [← Category.assoc, SSet.ι_chainComplexMap_f]
  rw [ι_chainGroupIsoFinsupp_hom]
  rw [← Category.assoc, ι_chainGroupIsoFinsupp_hom]
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro z
  change Finsupp.single (x : (TopCat.toSSet.obj X) _⦋n⦌) z.down =
    Finsupp.mapDomain Subtype.val (Finsupp.single x z.down)
  simp

theorem chainGroupIsoFinsupp_d_apply (X : TopCat.{u}) (n : ℕ)
    (c : SingularChainFinsupp X (n + 1)) :
    (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom
        (((TopCat.toSSet.obj X).chainComplex integerCoefficients).d (n + 1) n
          ((chainGroupIsoFinsupp (TopCat.toSSet.obj X) (n + 1)).inv c)) =
      singularFinsuppBoundary X n c := by
  have h := chainGroupIsoFinsupp_d X n
  have hc := congr($h c)
  simpa only [ConcreteCategory.comp_apply, Iso.inv_hom_id_apply,
    ModuleCat.hom_ofHom] using hc

theorem chainGroupIsoFinsupp_smallInclusion_apply
    {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X) (n : ℕ)
    (c : (TopCat.smallSingularSet U : SSet.{u}) _⦋n⦌ →₀ ℤ) :
    (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom
        ((smallSingularChainInclusion U).f n
          ((chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).inv c)) =
      Finsupp.mapDomain Subtype.val c := by
  have h := chainGroupIsoFinsupp_smallInclusion U n
  have hc := congr($h c)
  change (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom
      ((smallSingularChainInclusion U).f n
        ((chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).inv c)) =
    Finsupp.mapDomain Subtype.val c at hc
  exact hc

theorem smallSingularChainInclusion_f_injective
    {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X) (n : ℕ) :
    Function.Injective ((smallSingularChainInclusion U).f n) := by
  intro a b hab
  apply (ModuleCat.mono_iff_injective
    (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).hom).mp inferInstance
  let a' := (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).hom a
  let b' := (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).hom b
  apply Finsupp.mapDomain_injective Subtype.val_injective
  change Finsupp.mapDomain Subtype.val a' = Finsupp.mapDomain Subtype.val b'
  rw [← chainGroupIsoFinsupp_smallInclusion_apply U n a',
    ← chainGroupIsoFinsupp_smallInclusion_apply U n b']
  have ha' : (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).inv a' = a := by
    have h := congr($((chainGroupIsoFinsupp
      (TopCat.smallSingularSet U : SSet.{u}) n).hom_inv_id) a)
    change (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).inv
      ((chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).hom a) = a at h
    exact h
  have hb' : (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).inv b' = b := by
    have h := congr($((chainGroupIsoFinsupp
      (TopCat.smallSingularSet U : SSet.{u}) n).hom_inv_id) b)
    change (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).inv
      ((chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).hom b) = b at h
    exact h
  rw [ha', hb']
  exact congr_arg (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom hab

/-- Restrict a finitely supported singular chain to the subtype of simplices
small in one member of `U`, discarding any other terms. No support or cover
hypothesis is required here; `mapDomain_smallChainOfSupport` recovers the original
chain when every simplex in its support is small. -/
def smallChainOfSupport {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X) {n : ℕ}
    (c : SingularChainFinsupp X n) :
    (TopCat.smallSingularSet U : SSet.{u}) _⦋n⦌ →₀ ℤ :=
  Finsupp.subtypeDomain (fun x ↦ IsCoverSmall U x) c

theorem mapDomain_smallChainOfSupport {X : TopCat.{u}} {ι : Type*}
    (U : ι → Opens X) {n : ℕ} (c : SingularChainFinsupp X n)
    (hc : ∀ x ∈ c.support, IsCoverSmall U x) :
    Finsupp.mapDomain Subtype.val (smallChainOfSupport U c) = c := by
  classical
  change Finsupp.mapDomain (Function.Embedding.subtype (fun x ↦ IsCoverSmall U x))
      (Finsupp.subtypeDomain (fun x ↦ IsCoverSmall U x) c) = c
  rw [← Finsupp.embDomain_eq_mapDomain
    (Function.Embedding.subtype (fun x ↦ IsCoverSmall U x))]
  rw [← Finsupp.extendDomain_eq_embDomain_subtype]
  exact Finsupp.extendDomain_subtypeDomain c hc

theorem isCoverSmall_of_mem_mapDomain_small {X : TopCat.{u}} {ι : Type*}
    (U : ι → Opens X) {n : ℕ}
    (c : (TopCat.smallSingularSet U : SSet.{u}) _⦋n⦌ →₀ ℤ)
    {x : (TopCat.toSSet.obj X) _⦋n⦌}
    (hx : x ∈ (Finsupp.mapDomain Subtype.val c).support) :
    IsCoverSmall U x := by
  classical
  have hx' := Finsupp.mapDomain_support hx
  obtain ⟨y, hy, rfl⟩ := Finset.mem_image.mp hx'
  exact y.property

end AlgebraicTopology
open CategoryTheory Convexity TopologicalSpace
open scoped Simplicial

noncomputable section

namespace AlgebraicTopology

/-- The inclusion of cover-small integer singular chains is a quasi-isomorphism. -/
theorem quasiIso_smallSingularChainInclusion
    {X : TopCat.{u}} {ι : Type*} (U : ι → Opens X)
    (hU : TopologicalSpace.IsOpenCover U) :
    QuasiIso (smallSingularChainInclusion U) := by
  rw [quasiIso_iff]
  intro n
  have hprev : (ComplexShape.down ℕ).prev n = n + 1 := ChainComplex.prev ℕ n
  have hnext : (ComplexShape.down ℕ).next n = n - 1 := by
    rcases n with _ | n
    · exact ChainComplex.next_nat_zero
    · exact ChainComplex.next_nat_succ n
  rw [quasiIsoAt_iff' (smallSingularChainInclusion U) (n + 1) n (n - 1)
    hprev hnext]
  apply moduleCat_quasiIso_of_representatives
  · intro y hy
    change ((TopCat.toSSet.obj X).chainComplex integerCoefficients).X n at y
    change ((TopCat.toSSet.obj X).chainComplex integerCoefficients).d n (n - 1) y = 0 at hy
    let c : SingularChainFinsupp X n :=
      (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom y
    obtain ⟨N, hN⟩ := exists_singularSubdivisionIterate_chain_cover_small U hU c
    let cN := singularSubdivisionIterate X n N c
    let cs := smallChainOfSupport U cN
    let x := (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).inv cs
    have hcs : Finsupp.mapDomain Subtype.val cs = cN := by
      exact mapDomain_smallChainOfSupport U cN (fun _ hx ↦ hN hx)
    have hximage :
        (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom
            ((smallSingularChainInclusion U).f n x) = cN := by
      rw [show x = (chainGroupIsoFinsupp
        (TopCat.smallSingularSet U : SSet.{u}) n).inv cs from rfl,
        chainGroupIsoFinsupp_smallInclusion_apply, hcs]
    have hximage' :
        (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom
            ((SSet.chainComplexMap (TopCat.smallSingularSet U).ι
              integerCoefficients).f n x) = cN := by
      exact hximage
    have hxinc :
        (SSet.chainComplexMap (TopCat.smallSingularSet U).ι integerCoefficients).f n x =
          (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).inv cN := by
      apply (ModuleCat.mono_iff_injective
        (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom).mp inferInstance
      rw [hximage']
      have h := congr($((chainGroupIsoFinsupp
        (TopCat.toSSet.obj X) n).inv_hom_id) cN)
      change (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom
        ((chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).inv cN) = cN at h
      exact h.symm
    refine ⟨x, ?_, ?_⟩
    · change (smallSingularChainComplex U).d n (n - 1) x = 0
      rcases n with _ | k
      · rfl
      · change ((TopCat.smallSingularSet U : SSet.{u}).chainComplex
          integerCoefficients).d (k + 1) k x = 0
        have hcycle : singularFinsuppBoundary X k c = 0 := by
          rw [← chainGroupIsoFinsupp_d_apply X k c]
          have hy' : ((TopCat.toSSet.obj X).chainComplex integerCoefficients).d
                (k + 1) k y = 0 := hy
          have hinv : (chainGroupIsoFinsupp (TopCat.toSSet.obj X) (k + 1)).inv c = y := by
            have h := congr($((chainGroupIsoFinsupp
              (TopCat.toSSet.obj X) (k + 1)).hom_inv_id) y)
            exact h
          rw [hinv, hy']
          simp
        have hcNcycle : singularFinsuppBoundary X k cN = 0 := by
          dsimp [cN]
          rw [singularSubdivisionIterate_boundary, hcycle, map_zero]
        apply (ModuleCat.mono_iff_injective
          (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) k).hom).mp
            inferInstance
        rw [show x = (chainGroupIsoFinsupp
          (TopCat.smallSingularSet U : SSet.{u}) (k + 1)).inv cs from rfl,
          chainGroupIsoFinsupp_sSet_d_apply, map_zero]
        apply Finsupp.mapDomain_injective Subtype.val_injective
        rw [mapDomain_smallFinsuppBoundary, hcs, hcNcycle,
          Finsupp.mapDomain_zero]
    · let p := -(singularHomotopyIterate X n N c)
      let b := (chainGroupIsoFinsupp (TopCat.toSSet.obj X) (n + 1)).inv p
      refine ⟨b, ?_⟩
      dsimp [HomologicalComplex.shortComplexFunctor', smallSingularChainInclusion,
        singularChainComplexFunctor]
      change (SSet.chainComplexMap (TopCat.smallSingularSet U).ι
          integerCoefficients).f n x - y =
        ((TopCat.toSSet.obj X).chainComplex integerCoefficients).d (n + 1) n b
      apply (ModuleCat.mono_iff_injective
        (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom).mp inferInstance
      rw [map_sub, hximage']
      change cN - c = _
      rw [show b = (chainGroupIsoFinsupp
        (TopCat.toSSet.obj X) (n + 1)).inv p from rfl,
        chainGroupIsoFinsupp_d_apply]
      dsimp [p]
      rw [map_neg]
      rcases n with _ | k
      · rw [singularHomotopyIterate_degree_zero]
        module
      · have hcycle : singularFinsuppBoundary X k c = 0 := by
          rw [← chainGroupIsoFinsupp_d_apply X k c]
          have hinv : (chainGroupIsoFinsupp (TopCat.toSSet.obj X) (k + 1)).inv c = y := by
            have h := congr($((chainGroupIsoFinsupp
              (TopCat.toSSet.obj X) (k + 1)).hom_inv_id) y)
            exact h
          have hy' : ((TopCat.toSSet.obj X).chainComplex integerCoefficients).d
              (k + 1) k y = 0 := by simpa using hy
          rw [hinv, hy']
          simp
        have hh := singularHomotopyIterate_boundary X k N c
        rw [hcycle, map_zero] at hh
        simp only [add_zero] at hh
        rw [hh]
        module
  · intro x hx b hb
    classical
    dsimp [HomologicalComplex.shortComplexFunctor', smallSingularChainInclusion,
      smallSingularChainComplex, singularChainComplexFunctor] at hx hb ⊢
    let xs : ((TopCat.smallSingularSet U : SSet.{u}).chainComplex
      integerCoefficients).X n := x
    let bs : ((TopCat.toSSet.obj X).chainComplex
      integerCoefficients).X (n + 1) := b
    have hxs_cycle : ((TopCat.smallSingularSet U : SSet.{u}).chainComplex
        integerCoefficients).d n (n - 1) xs = 0 := by
      exact hx
    have hxs_boundary :
        (SSet.chainComplexMap (TopCat.smallSingularSet U).ι
          integerCoefficients).f n xs =
        ((TopCat.toSSet.obj X).chainComplex integerCoefficients).d
          (n + 1) n bs := by
      exact hb
    let cs := (chainGroupIsoFinsupp
      (TopCat.smallSingularSet U : SSet.{u}) n).hom xs
    let c : SingularChainFinsupp X n := Finsupp.mapDomain Subtype.val cs
    let cb : SingularChainFinsupp X (n + 1) :=
      (chainGroupIsoFinsupp (TopCat.toSSet.obj X) (n + 1)).hom bs
    have hxcs : (chainGroupIsoFinsupp
        (TopCat.smallSingularSet U : SSet.{u}) n).inv cs = xs := by
      have h := congr($((chainGroupIsoFinsupp
        (TopCat.smallSingularSet U : SSet.{u}) n).hom_inv_id) xs)
      exact h
    have hbcb : (chainGroupIsoFinsupp
        (TopCat.toSSet.obj X) (n + 1)).inv cb = bs := by
      have h := congr($((chainGroupIsoFinsupp
        (TopCat.toSSet.obj X) (n + 1)).hom_inv_id) bs)
      exact h
    have hc_boundary : c = singularFinsuppBoundary X n cb := by
      calc
        c = (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom
            ((SSet.chainComplexMap (TopCat.smallSingularSet U).ι
              integerCoefficients).f n xs) := by
                rw [← hxcs]
                exact (chainGroupIsoFinsupp_smallInclusion_apply U n cs).symm
        _ = (chainGroupIsoFinsupp (TopCat.toSSet.obj X) n).hom
            (((TopCat.toSSet.obj X).chainComplex integerCoefficients).d
              (n + 1) n bs) := congr_arg _ hxs_boundary
        _ = singularFinsuppBoundary X n cb := by
              rw [← hbcb, chainGroupIsoFinsupp_d_apply]
    have hc_small : ∀ y ∈ c.support, IsCoverSmall U y := by
      intro y hy
      exact isCoverSmall_of_mem_mapDomain_small U cs hy
    obtain ⟨N, hN⟩ :=
      exists_singularSubdivisionIterate_chain_cover_small U hU cb
    let corrected : SingularChainFinsupp X (n + 1) :=
      singularSubdivisionIterate X (n + 1) N cb +
        singularHomotopyIterate X n N c
    have hcorrected_small : ∀ y ∈ corrected.support, IsCoverSmall U y := by
      intro y hy
      dsimp [corrected] at hy
      rcases Finset.mem_union.mp (Finsupp.support_add hy) with hsd | hH
      · exact hN hsd
      · exact isCoverSmall_of_mem_singularHomotopyIterate U hc_small hH
    have hcorrected_boundary :
        singularFinsuppBoundary X n corrected = c := by
      dsimp [corrected]
      rw [map_add, singularSubdivisionIterate_boundary, ← hc_boundary]
      rcases n with _ | k
      · rw [singularHomotopyIterate_degree_zero]
        module
      · have hc_cycle : singularFinsuppBoundary X k c = 0 := by
          rw [show c = Finsupp.mapDomain Subtype.val cs from rfl,
            ← mapDomain_smallFinsuppBoundary U k cs]
          have hx' : ((TopCat.smallSingularSet U : SSet.{u}).chainComplex
              integerCoefficients).d (k + 1) k xs = 0 := by
            simpa using hxs_cycle
          rw [← chainGroupIsoFinsupp_sSet_d_apply]
          rw [hxcs, hx', map_zero, Finsupp.mapDomain_zero]
        have hH := singularHomotopyIterate_boundary X k N c
        rw [hc_cycle, map_zero] at hH
        simp only [add_zero] at hH
        rw [hH]
        module
    let correctedSmall := smallChainOfSupport U corrected
    let a := (chainGroupIsoFinsupp
      (TopCat.smallSingularSet U : SSet.{u}) (n + 1)).inv correctedSmall
    change ∃ a : ((TopCat.smallSingularSet U : SSet.{u}).chainComplex
      integerCoefficients).X (n + 1), xs =
        ((TopCat.smallSingularSet U : SSet.{u}).chainComplex
          integerCoefficients).d (n + 1) n a
    refine ⟨a, ?_⟩
    rw [← hxcs]
    apply (ModuleCat.mono_iff_injective
      (chainGroupIsoFinsupp (TopCat.smallSingularSet U : SSet.{u}) n).hom).mp
        inferInstance
    rw [show a = (chainGroupIsoFinsupp
      (TopCat.smallSingularSet U : SSet.{u}) (n + 1)).inv correctedSmall from rfl,
      chainGroupIsoFinsupp_sSet_d_apply]
    rw [Iso.inv_hom_id_apply]
    apply Finsupp.mapDomain_injective Subtype.val_injective
    rw [mapDomain_smallFinsuppBoundary, mapDomain_smallChainOfSupport U corrected
      (fun _ hy ↦ hcorrected_small _ hy), hcorrected_boundary]

end AlgebraicTopology
